name: Workflow Dispatch Test
run-name: ${{ inputs.run-name }}
on:
  workflow_dispatch:
    inputs:
      run-name:
        description: 'Name of the workflow run'
        required: true
        default: '0123456789'
        type: string
jobs:
  view-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh run list
        env:
          GH_TOKEN: ${{ github.token }}
